### ISSUE TITLE
crash after bain's briefing (black screen)

### ISSUE THREAD

**Issue by BadLucKWyvern** [polarathene/biglobby#36]
Application has crashed: C++ exception
[string "lib/units/player_team/logics/teamailogictra..."]:87: attempt to index field '?' (a nil value)
safe house raid mission, i haven't tested others...

help please :(

**Comment by polarathene** [comment]
Hello, sorry for the late response. The mod probably just needs to be sync'd to the latest game updates, I'll try sort that out for you later today.

**Comment by BadLucKWyvern** [comment]
Great THX... i can't play pd2 anymore without biglobby. Im depending of it
now :$

**Comment by polarathene** [comment]
@BadLucKWyvern Hi there, [I've released v2.39 here](https://github.com/polarathene/biglobby/releases/tag/v2.39), could you give it a try and let me know if it works for you? Thanks :)

**Comment by BadLucKWyvern** [comment]
in few hours ill :)

2017-04-26 6:53 GMT+02:00 Brennan Kinney <notifications@github.com>:

**Comment by polarathene** [comment]
@BadLucKWyvern Crimespree lobby(?) will not work as mentioned in [this issue](https://github.com/polarathene/biglobby/issues/37#issuecomment-297370366). It needs UI code to be patched which I do not have free time to do, if you can find another modder who can I'll push an update with the bug fix :)

I think regular game withoout this crimespree thing should work fine though.

**Comment by BadLucKWyvern** [comment]
Wed Apr 26 15:27:28 2017


Application has crashed: C++ exception
[string "lib/units/player_team/logics/teamailogictra..."]:87: attempt to index field '?' (a nil value)

i tryied the tar and the zip... the problem is still here :/cops raid safehouse 
+16 bots
Allow more bot = true

that was weird because i deleted the old folder and the old file in the mod folder and added the new one, and options didn't changed like if i didn't do the right thing...

**Comment by polarathene** [comment]
The error refers to a game code not my mod code, this also means the line number it provides is not valid. Does it work with less bots? I'm not sure what the payday gang count currently is(playable characters), but you do not want to have more than 1 of each character. I was working on a feature to work around that but life got in the way :(

Mods save data into a separate folder in the mods folder. So removing a mod and adding it won't delete the save data. I can't recall the name but it's pretty obvious, maybe `save`.

**Comment by polarathene** [comment]
Also I just pushed [v2.40](https://github.com/polarathene/biglobby/releases/tag/v2.40) which has a couple bug fixes, I don't think it'd make a difference here though.

**Comment by BadLucKWyvern** [comment]
lobby size 14
bot number 14
crash
lobby size 17 
bot number 16
crash
same log

so... is it lost ?

**Comment by BadLucKWyvern** [comment]
damn... i tryied big lobby as lone mod... and its working, there is a conflict somewhere :/

**Comment by BadLucKWyvern** [comment]
Conflict with BotWeapons mod... :,( ...

**Comment by BadLucKWyvern** [comment]
Sorry for spam, the bug was spotted in the bot weapon and equipment thread. and fixed, ive uploaded it and its working again !

Thxa lot for you support, you can close the sub :)

**Comment by polarathene** [comment]
Glad to hear :) Seems my mod is a bit popular at the moment with all the recent issues.
